# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roseapp', '0002_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='oshp_price',
            name='oproduct_Packingszie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roseapp.opackingsize', verbose_name='Packing'),
        ),
    ]
